
name_tool = "Flashtools"
type_tool = "Multi-Tools"
version_tool = "V.1"
coding_tool = "Python 3"
language_tool = "EN"
creator = "loxy0dev"
platform = "Windows 10/11 & Linux"
discord_server = "https://discord.gg/8mhuaJNpvs"
website = "Soon"
github_tool = "soon"
telegram = "soon"
url_config = "soon"
url_downloads = "soon"
license = "soon"
copyright = "soon"
